
services:
  api:
    build:
      context: ./movies
    container_name: cinema_api
    depends_on:
      - postgres
      - elasticsearch
      - minio
    env_file:
      - ./movies/.env
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "8000:8000"
    networks:
      - cinema_net

  etl_worker:
    image: python:3.12
    volumes:
      - ./movies:/app
    working_dir: /app
    entrypoint: ["./etl_worker.sh"]
    depends_on: [postgres, elasticsearch]
    env_file:
      - ./movies/.env
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - PG_DSN=postgresql://user:password@cinema_postgres:5432/cinema_db
    networks:
      - cinema_net

  videostream:
    build:
      context: ./videostream
      dockerfile: Dockerfile
    container_name: cinema_videostream
    volumes:
      - ./videostream:/app
    working_dir: /app
    depends_on:
      - minio
      - redis
    environment:
      - S3_BUCKET=movies
      - S3_ENDPOINT_URL=http://minio:9000
      - aws_access_key_id=minioadmin
      - aws_secret_access_key=minioadmin
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=20
    ports:
      - "8002:8002"
    networks:
      - cinema_net

  prometheus:
    image: prom/prometheus:latest
    container_name: cinema_prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - cinema_net

  grafana:
    image: grafana/grafana:latest
    container_name: cinema_grafana
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
      - ./deploy/grafana/provisioning/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - cinema_net
    depends_on:
      - prometheus
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cinema_jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # Web UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - cinema_net

  postgres:
    image: postgres:15-alpine
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: cinema_elasticsearch
    environment:
      - node.name=cinema_elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - cinema_net

  minio:
    image: minio/minio
    container_name: cinema_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - cinema_net

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/movies;
      /usr/bin/mc policy set public myminio/movies;
      exit 0;
      "
    networks:
      - cinema_net

  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    networks:
      - cinema_net

networks:
  cinema_net:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  minio_data:
