global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: 'cinema_api'
    static_configs:
      - targets: ['cinema_api:8000']

  - job_name: 'etl_worker'
    static_configs:
      - targets: ['etl_worker:8001']

  - job_name: 'videostream'
    static_configs:
      - targets: ['cinema_videostream:8002']
